blank_issues_enabled: false
contact_links:
  - name: Support via Discord
    url: https://discord.gg/tvgfpeCGaD
  - name: Security Vulnerability Reporting
    url: mailto:security@warfront.io
    about: Please report security vulnerabilities here.